function pulse_detector_ipcore_hw_setup(hFPGA,WriteFrameLength,ReadFrameLength)
% Copyright 2025 The MathWorks, Inc.

%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 9.12 (R2022a) at 14:09:52 on 21/09/2022.
% This function was created for the IP Core generated from design 'pulse_detector_ipcore'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0x400D0000, ...
	"AddressRange", 0x10000, ...
	"WriteDeviceName", "mwipcore0:mmwr0", ...
	"ReadDeviceName", "mwipcore0:mmrd0");

DUTPort_threshold = hdlcoder.DUTPort("threshold", ...
	"Direction", "INOUT", ...
	"DataType", numerictype(1,18,11), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

DUTPort_output_length = hdlcoder.DUTPort("output_length", ...
	"Direction", "INOUT", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x104");

mapPort(hFPGA, [DUTPort_threshold, DUTPort_output_length]);

%% AXI4-Stream
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream", ...
	"WriteEnable", true, ...
	"WriteDataWidth", 32, ...
	"WriteFrameLength", WriteFrameLength, ...
	"WriteDeviceName", "mwipcore0:mm2s0", ...
	"ReadEnable", true, ...
	"ReadDataWidth", 32, ...
	"ReadFrameLength", ReadFrameLength, ...
	"ReadDeviceName", "mwipcore0:s2mm0");

DUTPort_stream_in_data = hdlcoder.DUTPort("stream_in_data", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,16,14), ...
	"IsComplex", true, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream");

DUTPort_stream_out_data = hdlcoder.DUTPort("stream_out_data", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,16,14), ...
	"IsComplex", true, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream");

mapPort(hFPGA, [DUTPort_stream_in_data, DUTPort_stream_out_data]);

end
