// Copyright 2025 The MathWorks, Inc.
// -------------------------------------------------------------
// 
// File Name: custom_hdl_prj\hdlsrc\pulse_detector_ipcore\PulseDet_axi4_stream_slave.v
// Created: 2023-08-26 18:01:47
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PulseDet_axi4_stream_slave
// Source Path: PulseDet/PulseDet_axi4_stream_slave
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PulseDet_axi4_stream_slave
          (clk,
           reset,
           enb,
           AXI4_Stream_Slave_TDATA_0,
           AXI4_Stream_Slave_TDATA_1,
           AXI4_Stream_Slave_TVALID,
           user_ready,
           AXI4_Stream_Slave_TREADY,
           user_data_0,
           user_data_1,
           user_valid);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] AXI4_Stream_Slave_TDATA_0;  // ufix16
  input   [15:0] AXI4_Stream_Slave_TDATA_1;  // ufix16
  input   AXI4_Stream_Slave_TVALID;  // ufix1
  input   user_ready;  // ufix1
  output  AXI4_Stream_Slave_TREADY;  // ufix1
  output  [15:0] user_data_0;  // ufix16
  output  [15:0] user_data_1;  // ufix16
  output  user_valid;  // ufix1


  reg  fifo_rd_ack;  // ufix1
  wire [15:0] stream_in_fifo_user_data_0;  // ufix16
  wire fifo_empty;  // ufix1
  wire fifo_full;  // ufix1
  wire [15:0] stream_in_fifo_user_data_1;  // ufix16
  wire fifo_empty_neg;  // ufix1
  wire stream_in_user_valid;  // ufix1


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        fifo_rd_ack <= 1'b0;
      end
      else begin
        if (enb) begin
          fifo_rd_ack <= user_ready;
        end
      end
    end



  PulseDet_fifo_data u_PulseDet_fifo_data_inst (.clk(clk),
                                                .reset(reset),
                                                .enb(enb),
                                                .In(AXI4_Stream_Slave_TDATA_0),  // ufix16
                                                .Push(AXI4_Stream_Slave_TVALID),  // ufix1
                                                .Pop(fifo_rd_ack),  // ufix1
                                                .Out(stream_in_fifo_user_data_0),  // ufix16
                                                .Empty(fifo_empty),  // ufix1
                                                .Full(fifo_full)  // ufix1
                                                );

  assign AXI4_Stream_Slave_TREADY =  ~ fifo_full;



  assign user_data_0 = stream_in_fifo_user_data_0;

  PulseDet_fifo_data_block u_PulseDet_fifo_data_inst_1 (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .In(AXI4_Stream_Slave_TDATA_1),  // ufix16
                                                        .Push(AXI4_Stream_Slave_TVALID),  // ufix1
                                                        .Pop(fifo_rd_ack),  // ufix1
                                                        .Out(stream_in_fifo_user_data_1)  // ufix16
                                                        );

  assign user_data_1 = stream_in_fifo_user_data_1;

  assign fifo_empty_neg =  ~ fifo_empty;



  assign stream_in_user_valid = fifo_empty_neg & fifo_rd_ack;



  assign user_valid = stream_in_user_valid;

endmodule  // PulseDet_axi4_stream_slave

