// Copyright 2025 The MathWorks, Inc.
// -------------------------------------------------------------
// 
// File Name: custom_hdl_prj\hdlsrc\pulse_detector_ipcore\PulseDet_src_Oldest.v
// Created: 2023-08-26 18:01:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PulseDet_src_Oldest
// Source Path: pulse_detector_ipcore/Pulse Detector IP/Pulse Detector/Local Peak/Tapped Delay Enabled/tapped_delay_impl/Output 
// Ordering/Oldes
// Hierarchy Level: 6
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PulseDet_src_Oldest
          (u,
           d_1,
           d_2,
           d_3,
           d_4,
           d_5,
           d_6,
           d_7,
           d_8,
           d_9,
           d_10,
           y_0,
           y_1,
           y_2,
           y_3,
           y_4,
           y_5,
           y_6,
           y_7,
           y_8,
           y_9,
           y_10);


  input   signed [17:0] u;  // sfix18_En11
  input   signed [17:0] d_1;  // sfix18_En11
  input   signed [17:0] d_2;  // sfix18_En11
  input   signed [17:0] d_3;  // sfix18_En11
  input   signed [17:0] d_4;  // sfix18_En11
  input   signed [17:0] d_5;  // sfix18_En11
  input   signed [17:0] d_6;  // sfix18_En11
  input   signed [17:0] d_7;  // sfix18_En11
  input   signed [17:0] d_8;  // sfix18_En11
  input   signed [17:0] d_9;  // sfix18_En11
  input   signed [17:0] d_10;  // sfix18_En11
  output  signed [17:0] y_0;  // sfix18_En11
  output  signed [17:0] y_1;  // sfix18_En11
  output  signed [17:0] y_2;  // sfix18_En11
  output  signed [17:0] y_3;  // sfix18_En11
  output  signed [17:0] y_4;  // sfix18_En11
  output  signed [17:0] y_5;  // sfix18_En11
  output  signed [17:0] y_6;  // sfix18_En11
  output  signed [17:0] y_7;  // sfix18_En11
  output  signed [17:0] y_8;  // sfix18_En11
  output  signed [17:0] y_9;  // sfix18_En11
  output  signed [17:0] y_10;  // sfix18_En11




  assign y_0 = d_1;

  assign y_1 = d_2;

  assign y_2 = d_3;

  assign y_3 = d_4;

  assign y_4 = d_5;

  assign y_5 = d_6;

  assign y_6 = d_7;

  assign y_7 = d_8;

  assign y_8 = d_9;

  assign y_9 = d_10;

  assign y_10 = u;

endmodule  // PulseDet_src_Oldest

