// Copyright 2025 The MathWorks, Inc.
// -------------------------------------------------------------
// 
// File Name: custom_hdl_prj\hdlsrc\pulse_detector_ipcore\PulseDet_src_1D.v
// Created: 2023-08-26 18:01:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PulseDet_src_1D
// Source Path: pulse_detector_ipcore/Pulse Detector IP/Pulse Detector/Local Peak/Tapped Delay Enabled/Reshape/1D 
// Hierarchy Level: 5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PulseDet_src_1D
          (In1_0,
           In1_1,
           In1_2,
           In1_3,
           In1_4,
           In1_5,
           In1_6,
           In1_7,
           In1_8,
           In1_9,
           In1_10,
           Out1_0,
           Out1_1,
           Out1_2,
           Out1_3,
           Out1_4,
           Out1_5,
           Out1_6,
           Out1_7,
           Out1_8,
           Out1_9,
           Out1_10);


  input   signed [17:0] In1_0;  // sfix18_En11
  input   signed [17:0] In1_1;  // sfix18_En11
  input   signed [17:0] In1_2;  // sfix18_En11
  input   signed [17:0] In1_3;  // sfix18_En11
  input   signed [17:0] In1_4;  // sfix18_En11
  input   signed [17:0] In1_5;  // sfix18_En11
  input   signed [17:0] In1_6;  // sfix18_En11
  input   signed [17:0] In1_7;  // sfix18_En11
  input   signed [17:0] In1_8;  // sfix18_En11
  input   signed [17:0] In1_9;  // sfix18_En11
  input   signed [17:0] In1_10;  // sfix18_En11
  output  signed [17:0] Out1_0;  // sfix18_En11
  output  signed [17:0] Out1_1;  // sfix18_En11
  output  signed [17:0] Out1_2;  // sfix18_En11
  output  signed [17:0] Out1_3;  // sfix18_En11
  output  signed [17:0] Out1_4;  // sfix18_En11
  output  signed [17:0] Out1_5;  // sfix18_En11
  output  signed [17:0] Out1_6;  // sfix18_En11
  output  signed [17:0] Out1_7;  // sfix18_En11
  output  signed [17:0] Out1_8;  // sfix18_En11
  output  signed [17:0] Out1_9;  // sfix18_En11
  output  signed [17:0] Out1_10;  // sfix18_En11




  assign Out1_0 = In1_0;

  assign Out1_1 = In1_1;

  assign Out1_2 = In1_2;

  assign Out1_3 = In1_3;

  assign Out1_4 = In1_4;

  assign Out1_5 = In1_5;

  assign Out1_6 = In1_6;

  assign Out1_7 = In1_7;

  assign Out1_8 = In1_8;

  assign Out1_9 = In1_9;

  assign Out1_10 = In1_10;

endmodule  // PulseDet_src_1D

