// Copyright 2025 The MathWorks, Inc.
// -------------------------------------------------------------
// 
// File Name: custom_hdl_prj\hdlsrc\pulse_detector_ipcore\PulseDet_src_Local_Peak.v
// Created: 2023-08-26 18:01:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PulseDet_src_Local_Peak
// Source Path: pulse_detector_ipcore/Pulse Detector IP/Pulse Detector/Local Peak
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PulseDet_src_Local_Peak
          (clk,
           reset,
           enb,
           data_in_re,
           data_in_im,
           pow_in,
           valid_in,
           threshold,
           data_out_re,
           data_out_im,
           detected,
           valid_out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] data_in_re;  // sfix16_En14
  input   signed [15:0] data_in_im;  // sfix16_En14
  input   signed [17:0] pow_in;  // sfix18_En11
  input   valid_in;
  input   signed [17:0] threshold;  // sfix18_En11
  output  signed [15:0] data_out_re;  // sfix16_En14
  output  signed [15:0] data_out_im;  // sfix16_En14
  output  detected;
  output  valid_out;


  reg signed [15:0] Delay_reg_re [0:85];  // sfix16_En14 [86]
  reg signed [15:0] Delay_reg_im [0:85];  // sfix16_En14 [86]
  wire signed [15:0] Delay_reg_next_re [0:85];  // sfix16_En14 [86]
  wire signed [15:0] Delay_reg_next_im [0:85];  // sfix16_En14 [86]
  wire signed [15:0] Delay_out1_re;  // sfix16_En14
  wire signed [15:0] Delay_out1_im;  // sfix16_En14
  wire signed [17:0] Tapped_Delay_Enabled_out1_0;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_1;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_2;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_3;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_4;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_5;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_6;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_7;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_8;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_9;  // sfix18_En11
  wire signed [17:0] Tapped_Delay_Enabled_out1_10;  // sfix18_En11


  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_reg_re[0] <= 16'sb0000000000000000;
        Delay_reg_im[0] <= 16'sb0000000000000000;
        Delay_reg_re[1] <= 16'sb0000000000000000;
        Delay_reg_im[1] <= 16'sb0000000000000000;
        Delay_reg_re[2] <= 16'sb0000000000000000;
        Delay_reg_im[2] <= 16'sb0000000000000000;
        Delay_reg_re[3] <= 16'sb0000000000000000;
        Delay_reg_im[3] <= 16'sb0000000000000000;
        Delay_reg_re[4] <= 16'sb0000000000000000;
        Delay_reg_im[4] <= 16'sb0000000000000000;
        Delay_reg_re[5] <= 16'sb0000000000000000;
        Delay_reg_im[5] <= 16'sb0000000000000000;
        Delay_reg_re[6] <= 16'sb0000000000000000;
        Delay_reg_im[6] <= 16'sb0000000000000000;
        Delay_reg_re[7] <= 16'sb0000000000000000;
        Delay_reg_im[7] <= 16'sb0000000000000000;
        Delay_reg_re[8] <= 16'sb0000000000000000;
        Delay_reg_im[8] <= 16'sb0000000000000000;
        Delay_reg_re[9] <= 16'sb0000000000000000;
        Delay_reg_im[9] <= 16'sb0000000000000000;
        Delay_reg_re[10] <= 16'sb0000000000000000;
        Delay_reg_im[10] <= 16'sb0000000000000000;
        Delay_reg_re[11] <= 16'sb0000000000000000;
        Delay_reg_im[11] <= 16'sb0000000000000000;
        Delay_reg_re[12] <= 16'sb0000000000000000;
        Delay_reg_im[12] <= 16'sb0000000000000000;
        Delay_reg_re[13] <= 16'sb0000000000000000;
        Delay_reg_im[13] <= 16'sb0000000000000000;
        Delay_reg_re[14] <= 16'sb0000000000000000;
        Delay_reg_im[14] <= 16'sb0000000000000000;
        Delay_reg_re[15] <= 16'sb0000000000000000;
        Delay_reg_im[15] <= 16'sb0000000000000000;
        Delay_reg_re[16] <= 16'sb0000000000000000;
        Delay_reg_im[16] <= 16'sb0000000000000000;
        Delay_reg_re[17] <= 16'sb0000000000000000;
        Delay_reg_im[17] <= 16'sb0000000000000000;
        Delay_reg_re[18] <= 16'sb0000000000000000;
        Delay_reg_im[18] <= 16'sb0000000000000000;
        Delay_reg_re[19] <= 16'sb0000000000000000;
        Delay_reg_im[19] <= 16'sb0000000000000000;
        Delay_reg_re[20] <= 16'sb0000000000000000;
        Delay_reg_im[20] <= 16'sb0000000000000000;
        Delay_reg_re[21] <= 16'sb0000000000000000;
        Delay_reg_im[21] <= 16'sb0000000000000000;
        Delay_reg_re[22] <= 16'sb0000000000000000;
        Delay_reg_im[22] <= 16'sb0000000000000000;
        Delay_reg_re[23] <= 16'sb0000000000000000;
        Delay_reg_im[23] <= 16'sb0000000000000000;
        Delay_reg_re[24] <= 16'sb0000000000000000;
        Delay_reg_im[24] <= 16'sb0000000000000000;
        Delay_reg_re[25] <= 16'sb0000000000000000;
        Delay_reg_im[25] <= 16'sb0000000000000000;
        Delay_reg_re[26] <= 16'sb0000000000000000;
        Delay_reg_im[26] <= 16'sb0000000000000000;
        Delay_reg_re[27] <= 16'sb0000000000000000;
        Delay_reg_im[27] <= 16'sb0000000000000000;
        Delay_reg_re[28] <= 16'sb0000000000000000;
        Delay_reg_im[28] <= 16'sb0000000000000000;
        Delay_reg_re[29] <= 16'sb0000000000000000;
        Delay_reg_im[29] <= 16'sb0000000000000000;
        Delay_reg_re[30] <= 16'sb0000000000000000;
        Delay_reg_im[30] <= 16'sb0000000000000000;
        Delay_reg_re[31] <= 16'sb0000000000000000;
        Delay_reg_im[31] <= 16'sb0000000000000000;
        Delay_reg_re[32] <= 16'sb0000000000000000;
        Delay_reg_im[32] <= 16'sb0000000000000000;
        Delay_reg_re[33] <= 16'sb0000000000000000;
        Delay_reg_im[33] <= 16'sb0000000000000000;
        Delay_reg_re[34] <= 16'sb0000000000000000;
        Delay_reg_im[34] <= 16'sb0000000000000000;
        Delay_reg_re[35] <= 16'sb0000000000000000;
        Delay_reg_im[35] <= 16'sb0000000000000000;
        Delay_reg_re[36] <= 16'sb0000000000000000;
        Delay_reg_im[36] <= 16'sb0000000000000000;
        Delay_reg_re[37] <= 16'sb0000000000000000;
        Delay_reg_im[37] <= 16'sb0000000000000000;
        Delay_reg_re[38] <= 16'sb0000000000000000;
        Delay_reg_im[38] <= 16'sb0000000000000000;
        Delay_reg_re[39] <= 16'sb0000000000000000;
        Delay_reg_im[39] <= 16'sb0000000000000000;
        Delay_reg_re[40] <= 16'sb0000000000000000;
        Delay_reg_im[40] <= 16'sb0000000000000000;
        Delay_reg_re[41] <= 16'sb0000000000000000;
        Delay_reg_im[41] <= 16'sb0000000000000000;
        Delay_reg_re[42] <= 16'sb0000000000000000;
        Delay_reg_im[42] <= 16'sb0000000000000000;
        Delay_reg_re[43] <= 16'sb0000000000000000;
        Delay_reg_im[43] <= 16'sb0000000000000000;
        Delay_reg_re[44] <= 16'sb0000000000000000;
        Delay_reg_im[44] <= 16'sb0000000000000000;
        Delay_reg_re[45] <= 16'sb0000000000000000;
        Delay_reg_im[45] <= 16'sb0000000000000000;
        Delay_reg_re[46] <= 16'sb0000000000000000;
        Delay_reg_im[46] <= 16'sb0000000000000000;
        Delay_reg_re[47] <= 16'sb0000000000000000;
        Delay_reg_im[47] <= 16'sb0000000000000000;
        Delay_reg_re[48] <= 16'sb0000000000000000;
        Delay_reg_im[48] <= 16'sb0000000000000000;
        Delay_reg_re[49] <= 16'sb0000000000000000;
        Delay_reg_im[49] <= 16'sb0000000000000000;
        Delay_reg_re[50] <= 16'sb0000000000000000;
        Delay_reg_im[50] <= 16'sb0000000000000000;
        Delay_reg_re[51] <= 16'sb0000000000000000;
        Delay_reg_im[51] <= 16'sb0000000000000000;
        Delay_reg_re[52] <= 16'sb0000000000000000;
        Delay_reg_im[52] <= 16'sb0000000000000000;
        Delay_reg_re[53] <= 16'sb0000000000000000;
        Delay_reg_im[53] <= 16'sb0000000000000000;
        Delay_reg_re[54] <= 16'sb0000000000000000;
        Delay_reg_im[54] <= 16'sb0000000000000000;
        Delay_reg_re[55] <= 16'sb0000000000000000;
        Delay_reg_im[55] <= 16'sb0000000000000000;
        Delay_reg_re[56] <= 16'sb0000000000000000;
        Delay_reg_im[56] <= 16'sb0000000000000000;
        Delay_reg_re[57] <= 16'sb0000000000000000;
        Delay_reg_im[57] <= 16'sb0000000000000000;
        Delay_reg_re[58] <= 16'sb0000000000000000;
        Delay_reg_im[58] <= 16'sb0000000000000000;
        Delay_reg_re[59] <= 16'sb0000000000000000;
        Delay_reg_im[59] <= 16'sb0000000000000000;
        Delay_reg_re[60] <= 16'sb0000000000000000;
        Delay_reg_im[60] <= 16'sb0000000000000000;
        Delay_reg_re[61] <= 16'sb0000000000000000;
        Delay_reg_im[61] <= 16'sb0000000000000000;
        Delay_reg_re[62] <= 16'sb0000000000000000;
        Delay_reg_im[62] <= 16'sb0000000000000000;
        Delay_reg_re[63] <= 16'sb0000000000000000;
        Delay_reg_im[63] <= 16'sb0000000000000000;
        Delay_reg_re[64] <= 16'sb0000000000000000;
        Delay_reg_im[64] <= 16'sb0000000000000000;
        Delay_reg_re[65] <= 16'sb0000000000000000;
        Delay_reg_im[65] <= 16'sb0000000000000000;
        Delay_reg_re[66] <= 16'sb0000000000000000;
        Delay_reg_im[66] <= 16'sb0000000000000000;
        Delay_reg_re[67] <= 16'sb0000000000000000;
        Delay_reg_im[67] <= 16'sb0000000000000000;
        Delay_reg_re[68] <= 16'sb0000000000000000;
        Delay_reg_im[68] <= 16'sb0000000000000000;
        Delay_reg_re[69] <= 16'sb0000000000000000;
        Delay_reg_im[69] <= 16'sb0000000000000000;
        Delay_reg_re[70] <= 16'sb0000000000000000;
        Delay_reg_im[70] <= 16'sb0000000000000000;
        Delay_reg_re[71] <= 16'sb0000000000000000;
        Delay_reg_im[71] <= 16'sb0000000000000000;
        Delay_reg_re[72] <= 16'sb0000000000000000;
        Delay_reg_im[72] <= 16'sb0000000000000000;
        Delay_reg_re[73] <= 16'sb0000000000000000;
        Delay_reg_im[73] <= 16'sb0000000000000000;
        Delay_reg_re[74] <= 16'sb0000000000000000;
        Delay_reg_im[74] <= 16'sb0000000000000000;
        Delay_reg_re[75] <= 16'sb0000000000000000;
        Delay_reg_im[75] <= 16'sb0000000000000000;
        Delay_reg_re[76] <= 16'sb0000000000000000;
        Delay_reg_im[76] <= 16'sb0000000000000000;
        Delay_reg_re[77] <= 16'sb0000000000000000;
        Delay_reg_im[77] <= 16'sb0000000000000000;
        Delay_reg_re[78] <= 16'sb0000000000000000;
        Delay_reg_im[78] <= 16'sb0000000000000000;
        Delay_reg_re[79] <= 16'sb0000000000000000;
        Delay_reg_im[79] <= 16'sb0000000000000000;
        Delay_reg_re[80] <= 16'sb0000000000000000;
        Delay_reg_im[80] <= 16'sb0000000000000000;
        Delay_reg_re[81] <= 16'sb0000000000000000;
        Delay_reg_im[81] <= 16'sb0000000000000000;
        Delay_reg_re[82] <= 16'sb0000000000000000;
        Delay_reg_im[82] <= 16'sb0000000000000000;
        Delay_reg_re[83] <= 16'sb0000000000000000;
        Delay_reg_im[83] <= 16'sb0000000000000000;
        Delay_reg_re[84] <= 16'sb0000000000000000;
        Delay_reg_im[84] <= 16'sb0000000000000000;
        Delay_reg_re[85] <= 16'sb0000000000000000;
        Delay_reg_im[85] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_reg_re[0] <= Delay_reg_next_re[0];
          Delay_reg_im[0] <= Delay_reg_next_im[0];
          Delay_reg_re[1] <= Delay_reg_next_re[1];
          Delay_reg_im[1] <= Delay_reg_next_im[1];
          Delay_reg_re[2] <= Delay_reg_next_re[2];
          Delay_reg_im[2] <= Delay_reg_next_im[2];
          Delay_reg_re[3] <= Delay_reg_next_re[3];
          Delay_reg_im[3] <= Delay_reg_next_im[3];
          Delay_reg_re[4] <= Delay_reg_next_re[4];
          Delay_reg_im[4] <= Delay_reg_next_im[4];
          Delay_reg_re[5] <= Delay_reg_next_re[5];
          Delay_reg_im[5] <= Delay_reg_next_im[5];
          Delay_reg_re[6] <= Delay_reg_next_re[6];
          Delay_reg_im[6] <= Delay_reg_next_im[6];
          Delay_reg_re[7] <= Delay_reg_next_re[7];
          Delay_reg_im[7] <= Delay_reg_next_im[7];
          Delay_reg_re[8] <= Delay_reg_next_re[8];
          Delay_reg_im[8] <= Delay_reg_next_im[8];
          Delay_reg_re[9] <= Delay_reg_next_re[9];
          Delay_reg_im[9] <= Delay_reg_next_im[9];
          Delay_reg_re[10] <= Delay_reg_next_re[10];
          Delay_reg_im[10] <= Delay_reg_next_im[10];
          Delay_reg_re[11] <= Delay_reg_next_re[11];
          Delay_reg_im[11] <= Delay_reg_next_im[11];
          Delay_reg_re[12] <= Delay_reg_next_re[12];
          Delay_reg_im[12] <= Delay_reg_next_im[12];
          Delay_reg_re[13] <= Delay_reg_next_re[13];
          Delay_reg_im[13] <= Delay_reg_next_im[13];
          Delay_reg_re[14] <= Delay_reg_next_re[14];
          Delay_reg_im[14] <= Delay_reg_next_im[14];
          Delay_reg_re[15] <= Delay_reg_next_re[15];
          Delay_reg_im[15] <= Delay_reg_next_im[15];
          Delay_reg_re[16] <= Delay_reg_next_re[16];
          Delay_reg_im[16] <= Delay_reg_next_im[16];
          Delay_reg_re[17] <= Delay_reg_next_re[17];
          Delay_reg_im[17] <= Delay_reg_next_im[17];
          Delay_reg_re[18] <= Delay_reg_next_re[18];
          Delay_reg_im[18] <= Delay_reg_next_im[18];
          Delay_reg_re[19] <= Delay_reg_next_re[19];
          Delay_reg_im[19] <= Delay_reg_next_im[19];
          Delay_reg_re[20] <= Delay_reg_next_re[20];
          Delay_reg_im[20] <= Delay_reg_next_im[20];
          Delay_reg_re[21] <= Delay_reg_next_re[21];
          Delay_reg_im[21] <= Delay_reg_next_im[21];
          Delay_reg_re[22] <= Delay_reg_next_re[22];
          Delay_reg_im[22] <= Delay_reg_next_im[22];
          Delay_reg_re[23] <= Delay_reg_next_re[23];
          Delay_reg_im[23] <= Delay_reg_next_im[23];
          Delay_reg_re[24] <= Delay_reg_next_re[24];
          Delay_reg_im[24] <= Delay_reg_next_im[24];
          Delay_reg_re[25] <= Delay_reg_next_re[25];
          Delay_reg_im[25] <= Delay_reg_next_im[25];
          Delay_reg_re[26] <= Delay_reg_next_re[26];
          Delay_reg_im[26] <= Delay_reg_next_im[26];
          Delay_reg_re[27] <= Delay_reg_next_re[27];
          Delay_reg_im[27] <= Delay_reg_next_im[27];
          Delay_reg_re[28] <= Delay_reg_next_re[28];
          Delay_reg_im[28] <= Delay_reg_next_im[28];
          Delay_reg_re[29] <= Delay_reg_next_re[29];
          Delay_reg_im[29] <= Delay_reg_next_im[29];
          Delay_reg_re[30] <= Delay_reg_next_re[30];
          Delay_reg_im[30] <= Delay_reg_next_im[30];
          Delay_reg_re[31] <= Delay_reg_next_re[31];
          Delay_reg_im[31] <= Delay_reg_next_im[31];
          Delay_reg_re[32] <= Delay_reg_next_re[32];
          Delay_reg_im[32] <= Delay_reg_next_im[32];
          Delay_reg_re[33] <= Delay_reg_next_re[33];
          Delay_reg_im[33] <= Delay_reg_next_im[33];
          Delay_reg_re[34] <= Delay_reg_next_re[34];
          Delay_reg_im[34] <= Delay_reg_next_im[34];
          Delay_reg_re[35] <= Delay_reg_next_re[35];
          Delay_reg_im[35] <= Delay_reg_next_im[35];
          Delay_reg_re[36] <= Delay_reg_next_re[36];
          Delay_reg_im[36] <= Delay_reg_next_im[36];
          Delay_reg_re[37] <= Delay_reg_next_re[37];
          Delay_reg_im[37] <= Delay_reg_next_im[37];
          Delay_reg_re[38] <= Delay_reg_next_re[38];
          Delay_reg_im[38] <= Delay_reg_next_im[38];
          Delay_reg_re[39] <= Delay_reg_next_re[39];
          Delay_reg_im[39] <= Delay_reg_next_im[39];
          Delay_reg_re[40] <= Delay_reg_next_re[40];
          Delay_reg_im[40] <= Delay_reg_next_im[40];
          Delay_reg_re[41] <= Delay_reg_next_re[41];
          Delay_reg_im[41] <= Delay_reg_next_im[41];
          Delay_reg_re[42] <= Delay_reg_next_re[42];
          Delay_reg_im[42] <= Delay_reg_next_im[42];
          Delay_reg_re[43] <= Delay_reg_next_re[43];
          Delay_reg_im[43] <= Delay_reg_next_im[43];
          Delay_reg_re[44] <= Delay_reg_next_re[44];
          Delay_reg_im[44] <= Delay_reg_next_im[44];
          Delay_reg_re[45] <= Delay_reg_next_re[45];
          Delay_reg_im[45] <= Delay_reg_next_im[45];
          Delay_reg_re[46] <= Delay_reg_next_re[46];
          Delay_reg_im[46] <= Delay_reg_next_im[46];
          Delay_reg_re[47] <= Delay_reg_next_re[47];
          Delay_reg_im[47] <= Delay_reg_next_im[47];
          Delay_reg_re[48] <= Delay_reg_next_re[48];
          Delay_reg_im[48] <= Delay_reg_next_im[48];
          Delay_reg_re[49] <= Delay_reg_next_re[49];
          Delay_reg_im[49] <= Delay_reg_next_im[49];
          Delay_reg_re[50] <= Delay_reg_next_re[50];
          Delay_reg_im[50] <= Delay_reg_next_im[50];
          Delay_reg_re[51] <= Delay_reg_next_re[51];
          Delay_reg_im[51] <= Delay_reg_next_im[51];
          Delay_reg_re[52] <= Delay_reg_next_re[52];
          Delay_reg_im[52] <= Delay_reg_next_im[52];
          Delay_reg_re[53] <= Delay_reg_next_re[53];
          Delay_reg_im[53] <= Delay_reg_next_im[53];
          Delay_reg_re[54] <= Delay_reg_next_re[54];
          Delay_reg_im[54] <= Delay_reg_next_im[54];
          Delay_reg_re[55] <= Delay_reg_next_re[55];
          Delay_reg_im[55] <= Delay_reg_next_im[55];
          Delay_reg_re[56] <= Delay_reg_next_re[56];
          Delay_reg_im[56] <= Delay_reg_next_im[56];
          Delay_reg_re[57] <= Delay_reg_next_re[57];
          Delay_reg_im[57] <= Delay_reg_next_im[57];
          Delay_reg_re[58] <= Delay_reg_next_re[58];
          Delay_reg_im[58] <= Delay_reg_next_im[58];
          Delay_reg_re[59] <= Delay_reg_next_re[59];
          Delay_reg_im[59] <= Delay_reg_next_im[59];
          Delay_reg_re[60] <= Delay_reg_next_re[60];
          Delay_reg_im[60] <= Delay_reg_next_im[60];
          Delay_reg_re[61] <= Delay_reg_next_re[61];
          Delay_reg_im[61] <= Delay_reg_next_im[61];
          Delay_reg_re[62] <= Delay_reg_next_re[62];
          Delay_reg_im[62] <= Delay_reg_next_im[62];
          Delay_reg_re[63] <= Delay_reg_next_re[63];
          Delay_reg_im[63] <= Delay_reg_next_im[63];
          Delay_reg_re[64] <= Delay_reg_next_re[64];
          Delay_reg_im[64] <= Delay_reg_next_im[64];
          Delay_reg_re[65] <= Delay_reg_next_re[65];
          Delay_reg_im[65] <= Delay_reg_next_im[65];
          Delay_reg_re[66] <= Delay_reg_next_re[66];
          Delay_reg_im[66] <= Delay_reg_next_im[66];
          Delay_reg_re[67] <= Delay_reg_next_re[67];
          Delay_reg_im[67] <= Delay_reg_next_im[67];
          Delay_reg_re[68] <= Delay_reg_next_re[68];
          Delay_reg_im[68] <= Delay_reg_next_im[68];
          Delay_reg_re[69] <= Delay_reg_next_re[69];
          Delay_reg_im[69] <= Delay_reg_next_im[69];
          Delay_reg_re[70] <= Delay_reg_next_re[70];
          Delay_reg_im[70] <= Delay_reg_next_im[70];
          Delay_reg_re[71] <= Delay_reg_next_re[71];
          Delay_reg_im[71] <= Delay_reg_next_im[71];
          Delay_reg_re[72] <= Delay_reg_next_re[72];
          Delay_reg_im[72] <= Delay_reg_next_im[72];
          Delay_reg_re[73] <= Delay_reg_next_re[73];
          Delay_reg_im[73] <= Delay_reg_next_im[73];
          Delay_reg_re[74] <= Delay_reg_next_re[74];
          Delay_reg_im[74] <= Delay_reg_next_im[74];
          Delay_reg_re[75] <= Delay_reg_next_re[75];
          Delay_reg_im[75] <= Delay_reg_next_im[75];
          Delay_reg_re[76] <= Delay_reg_next_re[76];
          Delay_reg_im[76] <= Delay_reg_next_im[76];
          Delay_reg_re[77] <= Delay_reg_next_re[77];
          Delay_reg_im[77] <= Delay_reg_next_im[77];
          Delay_reg_re[78] <= Delay_reg_next_re[78];
          Delay_reg_im[78] <= Delay_reg_next_im[78];
          Delay_reg_re[79] <= Delay_reg_next_re[79];
          Delay_reg_im[79] <= Delay_reg_next_im[79];
          Delay_reg_re[80] <= Delay_reg_next_re[80];
          Delay_reg_im[80] <= Delay_reg_next_im[80];
          Delay_reg_re[81] <= Delay_reg_next_re[81];
          Delay_reg_im[81] <= Delay_reg_next_im[81];
          Delay_reg_re[82] <= Delay_reg_next_re[82];
          Delay_reg_im[82] <= Delay_reg_next_im[82];
          Delay_reg_re[83] <= Delay_reg_next_re[83];
          Delay_reg_im[83] <= Delay_reg_next_im[83];
          Delay_reg_re[84] <= Delay_reg_next_re[84];
          Delay_reg_im[84] <= Delay_reg_next_im[84];
          Delay_reg_re[85] <= Delay_reg_next_re[85];
          Delay_reg_im[85] <= Delay_reg_next_im[85];
        end
      end
    end

  assign Delay_out1_re = Delay_reg_re[85];
  assign Delay_out1_im = Delay_reg_im[85];
  assign Delay_reg_next_re[0] = data_in_re;
  assign Delay_reg_next_im[0] = data_in_im;
  assign Delay_reg_next_re[1] = Delay_reg_re[0];
  assign Delay_reg_next_im[1] = Delay_reg_im[0];
  assign Delay_reg_next_re[2] = Delay_reg_re[1];
  assign Delay_reg_next_im[2] = Delay_reg_im[1];
  assign Delay_reg_next_re[3] = Delay_reg_re[2];
  assign Delay_reg_next_im[3] = Delay_reg_im[2];
  assign Delay_reg_next_re[4] = Delay_reg_re[3];
  assign Delay_reg_next_im[4] = Delay_reg_im[3];
  assign Delay_reg_next_re[5] = Delay_reg_re[4];
  assign Delay_reg_next_im[5] = Delay_reg_im[4];
  assign Delay_reg_next_re[6] = Delay_reg_re[5];
  assign Delay_reg_next_im[6] = Delay_reg_im[5];
  assign Delay_reg_next_re[7] = Delay_reg_re[6];
  assign Delay_reg_next_im[7] = Delay_reg_im[6];
  assign Delay_reg_next_re[8] = Delay_reg_re[7];
  assign Delay_reg_next_im[8] = Delay_reg_im[7];
  assign Delay_reg_next_re[9] = Delay_reg_re[8];
  assign Delay_reg_next_im[9] = Delay_reg_im[8];
  assign Delay_reg_next_re[10] = Delay_reg_re[9];
  assign Delay_reg_next_im[10] = Delay_reg_im[9];
  assign Delay_reg_next_re[11] = Delay_reg_re[10];
  assign Delay_reg_next_im[11] = Delay_reg_im[10];
  assign Delay_reg_next_re[12] = Delay_reg_re[11];
  assign Delay_reg_next_im[12] = Delay_reg_im[11];
  assign Delay_reg_next_re[13] = Delay_reg_re[12];
  assign Delay_reg_next_im[13] = Delay_reg_im[12];
  assign Delay_reg_next_re[14] = Delay_reg_re[13];
  assign Delay_reg_next_im[14] = Delay_reg_im[13];
  assign Delay_reg_next_re[15] = Delay_reg_re[14];
  assign Delay_reg_next_im[15] = Delay_reg_im[14];
  assign Delay_reg_next_re[16] = Delay_reg_re[15];
  assign Delay_reg_next_im[16] = Delay_reg_im[15];
  assign Delay_reg_next_re[17] = Delay_reg_re[16];
  assign Delay_reg_next_im[17] = Delay_reg_im[16];
  assign Delay_reg_next_re[18] = Delay_reg_re[17];
  assign Delay_reg_next_im[18] = Delay_reg_im[17];
  assign Delay_reg_next_re[19] = Delay_reg_re[18];
  assign Delay_reg_next_im[19] = Delay_reg_im[18];
  assign Delay_reg_next_re[20] = Delay_reg_re[19];
  assign Delay_reg_next_im[20] = Delay_reg_im[19];
  assign Delay_reg_next_re[21] = Delay_reg_re[20];
  assign Delay_reg_next_im[21] = Delay_reg_im[20];
  assign Delay_reg_next_re[22] = Delay_reg_re[21];
  assign Delay_reg_next_im[22] = Delay_reg_im[21];
  assign Delay_reg_next_re[23] = Delay_reg_re[22];
  assign Delay_reg_next_im[23] = Delay_reg_im[22];
  assign Delay_reg_next_re[24] = Delay_reg_re[23];
  assign Delay_reg_next_im[24] = Delay_reg_im[23];
  assign Delay_reg_next_re[25] = Delay_reg_re[24];
  assign Delay_reg_next_im[25] = Delay_reg_im[24];
  assign Delay_reg_next_re[26] = Delay_reg_re[25];
  assign Delay_reg_next_im[26] = Delay_reg_im[25];
  assign Delay_reg_next_re[27] = Delay_reg_re[26];
  assign Delay_reg_next_im[27] = Delay_reg_im[26];
  assign Delay_reg_next_re[28] = Delay_reg_re[27];
  assign Delay_reg_next_im[28] = Delay_reg_im[27];
  assign Delay_reg_next_re[29] = Delay_reg_re[28];
  assign Delay_reg_next_im[29] = Delay_reg_im[28];
  assign Delay_reg_next_re[30] = Delay_reg_re[29];
  assign Delay_reg_next_im[30] = Delay_reg_im[29];
  assign Delay_reg_next_re[31] = Delay_reg_re[30];
  assign Delay_reg_next_im[31] = Delay_reg_im[30];
  assign Delay_reg_next_re[32] = Delay_reg_re[31];
  assign Delay_reg_next_im[32] = Delay_reg_im[31];
  assign Delay_reg_next_re[33] = Delay_reg_re[32];
  assign Delay_reg_next_im[33] = Delay_reg_im[32];
  assign Delay_reg_next_re[34] = Delay_reg_re[33];
  assign Delay_reg_next_im[34] = Delay_reg_im[33];
  assign Delay_reg_next_re[35] = Delay_reg_re[34];
  assign Delay_reg_next_im[35] = Delay_reg_im[34];
  assign Delay_reg_next_re[36] = Delay_reg_re[35];
  assign Delay_reg_next_im[36] = Delay_reg_im[35];
  assign Delay_reg_next_re[37] = Delay_reg_re[36];
  assign Delay_reg_next_im[37] = Delay_reg_im[36];
  assign Delay_reg_next_re[38] = Delay_reg_re[37];
  assign Delay_reg_next_im[38] = Delay_reg_im[37];
  assign Delay_reg_next_re[39] = Delay_reg_re[38];
  assign Delay_reg_next_im[39] = Delay_reg_im[38];
  assign Delay_reg_next_re[40] = Delay_reg_re[39];
  assign Delay_reg_next_im[40] = Delay_reg_im[39];
  assign Delay_reg_next_re[41] = Delay_reg_re[40];
  assign Delay_reg_next_im[41] = Delay_reg_im[40];
  assign Delay_reg_next_re[42] = Delay_reg_re[41];
  assign Delay_reg_next_im[42] = Delay_reg_im[41];
  assign Delay_reg_next_re[43] = Delay_reg_re[42];
  assign Delay_reg_next_im[43] = Delay_reg_im[42];
  assign Delay_reg_next_re[44] = Delay_reg_re[43];
  assign Delay_reg_next_im[44] = Delay_reg_im[43];
  assign Delay_reg_next_re[45] = Delay_reg_re[44];
  assign Delay_reg_next_im[45] = Delay_reg_im[44];
  assign Delay_reg_next_re[46] = Delay_reg_re[45];
  assign Delay_reg_next_im[46] = Delay_reg_im[45];
  assign Delay_reg_next_re[47] = Delay_reg_re[46];
  assign Delay_reg_next_im[47] = Delay_reg_im[46];
  assign Delay_reg_next_re[48] = Delay_reg_re[47];
  assign Delay_reg_next_im[48] = Delay_reg_im[47];
  assign Delay_reg_next_re[49] = Delay_reg_re[48];
  assign Delay_reg_next_im[49] = Delay_reg_im[48];
  assign Delay_reg_next_re[50] = Delay_reg_re[49];
  assign Delay_reg_next_im[50] = Delay_reg_im[49];
  assign Delay_reg_next_re[51] = Delay_reg_re[50];
  assign Delay_reg_next_im[51] = Delay_reg_im[50];
  assign Delay_reg_next_re[52] = Delay_reg_re[51];
  assign Delay_reg_next_im[52] = Delay_reg_im[51];
  assign Delay_reg_next_re[53] = Delay_reg_re[52];
  assign Delay_reg_next_im[53] = Delay_reg_im[52];
  assign Delay_reg_next_re[54] = Delay_reg_re[53];
  assign Delay_reg_next_im[54] = Delay_reg_im[53];
  assign Delay_reg_next_re[55] = Delay_reg_re[54];
  assign Delay_reg_next_im[55] = Delay_reg_im[54];
  assign Delay_reg_next_re[56] = Delay_reg_re[55];
  assign Delay_reg_next_im[56] = Delay_reg_im[55];
  assign Delay_reg_next_re[57] = Delay_reg_re[56];
  assign Delay_reg_next_im[57] = Delay_reg_im[56];
  assign Delay_reg_next_re[58] = Delay_reg_re[57];
  assign Delay_reg_next_im[58] = Delay_reg_im[57];
  assign Delay_reg_next_re[59] = Delay_reg_re[58];
  assign Delay_reg_next_im[59] = Delay_reg_im[58];
  assign Delay_reg_next_re[60] = Delay_reg_re[59];
  assign Delay_reg_next_im[60] = Delay_reg_im[59];
  assign Delay_reg_next_re[61] = Delay_reg_re[60];
  assign Delay_reg_next_im[61] = Delay_reg_im[60];
  assign Delay_reg_next_re[62] = Delay_reg_re[61];
  assign Delay_reg_next_im[62] = Delay_reg_im[61];
  assign Delay_reg_next_re[63] = Delay_reg_re[62];
  assign Delay_reg_next_im[63] = Delay_reg_im[62];
  assign Delay_reg_next_re[64] = Delay_reg_re[63];
  assign Delay_reg_next_im[64] = Delay_reg_im[63];
  assign Delay_reg_next_re[65] = Delay_reg_re[64];
  assign Delay_reg_next_im[65] = Delay_reg_im[64];
  assign Delay_reg_next_re[66] = Delay_reg_re[65];
  assign Delay_reg_next_im[66] = Delay_reg_im[65];
  assign Delay_reg_next_re[67] = Delay_reg_re[66];
  assign Delay_reg_next_im[67] = Delay_reg_im[66];
  assign Delay_reg_next_re[68] = Delay_reg_re[67];
  assign Delay_reg_next_im[68] = Delay_reg_im[67];
  assign Delay_reg_next_re[69] = Delay_reg_re[68];
  assign Delay_reg_next_im[69] = Delay_reg_im[68];
  assign Delay_reg_next_re[70] = Delay_reg_re[69];
  assign Delay_reg_next_im[70] = Delay_reg_im[69];
  assign Delay_reg_next_re[71] = Delay_reg_re[70];
  assign Delay_reg_next_im[71] = Delay_reg_im[70];
  assign Delay_reg_next_re[72] = Delay_reg_re[71];
  assign Delay_reg_next_im[72] = Delay_reg_im[71];
  assign Delay_reg_next_re[73] = Delay_reg_re[72];
  assign Delay_reg_next_im[73] = Delay_reg_im[72];
  assign Delay_reg_next_re[74] = Delay_reg_re[73];
  assign Delay_reg_next_im[74] = Delay_reg_im[73];
  assign Delay_reg_next_re[75] = Delay_reg_re[74];
  assign Delay_reg_next_im[75] = Delay_reg_im[74];
  assign Delay_reg_next_re[76] = Delay_reg_re[75];
  assign Delay_reg_next_im[76] = Delay_reg_im[75];
  assign Delay_reg_next_re[77] = Delay_reg_re[76];
  assign Delay_reg_next_im[77] = Delay_reg_im[76];
  assign Delay_reg_next_re[78] = Delay_reg_re[77];
  assign Delay_reg_next_im[78] = Delay_reg_im[77];
  assign Delay_reg_next_re[79] = Delay_reg_re[78];
  assign Delay_reg_next_im[79] = Delay_reg_im[78];
  assign Delay_reg_next_re[80] = Delay_reg_re[79];
  assign Delay_reg_next_im[80] = Delay_reg_im[79];
  assign Delay_reg_next_re[81] = Delay_reg_re[80];
  assign Delay_reg_next_im[81] = Delay_reg_im[80];
  assign Delay_reg_next_re[82] = Delay_reg_re[81];
  assign Delay_reg_next_im[82] = Delay_reg_im[81];
  assign Delay_reg_next_re[83] = Delay_reg_re[82];
  assign Delay_reg_next_im[83] = Delay_reg_im[82];
  assign Delay_reg_next_re[84] = Delay_reg_re[83];
  assign Delay_reg_next_im[84] = Delay_reg_im[83];
  assign Delay_reg_next_re[85] = Delay_reg_re[84];
  assign Delay_reg_next_im[85] = Delay_reg_im[84];



  assign data_out_re = Delay_out1_re;

  assign data_out_im = Delay_out1_im;

  PulseDet_src_Tapped_Delay_Enabled u_Tapped_Delay_Enabled (.clk(clk),
                                                            .reset(reset),
                                                            .enb(enb),
                                                            .u(pow_in),  // sfix18_En11
                                                            .en(valid_in),
                                                            .y_0(Tapped_Delay_Enabled_out1_0),  // sfix18_En11
                                                            .y_1(Tapped_Delay_Enabled_out1_1),  // sfix18_En11
                                                            .y_2(Tapped_Delay_Enabled_out1_2),  // sfix18_En11
                                                            .y_3(Tapped_Delay_Enabled_out1_3),  // sfix18_En11
                                                            .y_4(Tapped_Delay_Enabled_out1_4),  // sfix18_En11
                                                            .y_5(Tapped_Delay_Enabled_out1_5),  // sfix18_En11
                                                            .y_6(Tapped_Delay_Enabled_out1_6),  // sfix18_En11
                                                            .y_7(Tapped_Delay_Enabled_out1_7),  // sfix18_En11
                                                            .y_8(Tapped_Delay_Enabled_out1_8),  // sfix18_En11
                                                            .y_9(Tapped_Delay_Enabled_out1_9),  // sfix18_En11
                                                            .y_10(Tapped_Delay_Enabled_out1_10)  // sfix18_En11
                                                            );

  // Use hdlfimath (floor & wrap) when possible
  // to reduce hardware resource usage
  // (Toolbar > Edit Data > Ports & Data Manager) 
  PulseDet_src_MATLAB_Function u_MATLAB_Function (.threshold(threshold),  // sfix18_En11
                                                  .DataBuff_0(Tapped_Delay_Enabled_out1_0),  // sfix18_En11
                                                  .DataBuff_1(Tapped_Delay_Enabled_out1_1),  // sfix18_En11
                                                  .DataBuff_2(Tapped_Delay_Enabled_out1_2),  // sfix18_En11
                                                  .DataBuff_3(Tapped_Delay_Enabled_out1_3),  // sfix18_En11
                                                  .DataBuff_4(Tapped_Delay_Enabled_out1_4),  // sfix18_En11
                                                  .DataBuff_5(Tapped_Delay_Enabled_out1_5),  // sfix18_En11
                                                  .DataBuff_6(Tapped_Delay_Enabled_out1_6),  // sfix18_En11
                                                  .DataBuff_7(Tapped_Delay_Enabled_out1_7),  // sfix18_En11
                                                  .DataBuff_8(Tapped_Delay_Enabled_out1_8),  // sfix18_En11
                                                  .DataBuff_9(Tapped_Delay_Enabled_out1_9),  // sfix18_En11
                                                  .DataBuff_10(Tapped_Delay_Enabled_out1_10),  // sfix18_En11
                                                  .detected(detected)
                                                  );

  assign valid_out = valid_in;

endmodule  // PulseDet_src_Local_Peak

