// Copyright 2025 The MathWorks, Inc.
// -------------------------------------------------------------
// 
// File Name: custom_hdl_prj\hdlsrc\pulse_detector_ipcore\PulseDet_axi4_stream_master.v
// Created: 2023-08-26 18:01:47
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PulseDet_axi4_stream_master
// Source Path: PulseDet/PulseDet_axi4_stream_master
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PulseDet_axi4_stream_master
          (clk,
           reset,
           enb,
           AXI4_Stream_Master_TREADY,
           user_data_0,
           user_data_1,
           user_valid,
           write_packet_size_axi4_stream_master,
           AXI4_Stream_Master_TDATA_0,
           AXI4_Stream_Master_TDATA_1,
           AXI4_Stream_Master_TVALID,
           AXI4_Stream_Master_TLAST,
           user_ready);


  input   clk;
  input   reset;
  input   enb;
  input   AXI4_Stream_Master_TREADY;  // ufix1
  input   [15:0] user_data_0;  // ufix16
  input   [15:0] user_data_1;  // ufix16
  input   user_valid;  // ufix1
  input   [31:0] write_packet_size_axi4_stream_master;  // ufix32
  output  [15:0] AXI4_Stream_Master_TDATA_0;  // ufix16
  output  [15:0] AXI4_Stream_Master_TDATA_1;  // ufix16
  output  AXI4_Stream_Master_TVALID;  // ufix1
  output  AXI4_Stream_Master_TLAST;  // ufix1
  output  user_ready;  // ufix1


  wire [15:0] AXI4_Stream_Master_TDATA_0_1;  // ufix16
  wire fifo_empty_data;  // ufix1
  wire fifo_afull_data;  // ufix1
  wire [15:0] AXI4_Stream_Master_TDATA_1_1;  // ufix16
  wire [31:0] const_1;  // ufix32
  wire [31:0] tlast_size_value;  // ufix32
  wire reg_packet_size_strobe;  // ufix1
  wire auto_tlast;  // ufix1
  wire reset_TLAST;  // ufix1
  reg [31:0] tlast_counter_out;  // ufix32
  wire relop_relop1;
  wire internal_ready;  // ufix1


  PulseDet_fifo_data_OUT u_PulseDet_fifo_data_OUT_inst (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .In(user_data_0),  // ufix16
                                                        .Push(user_valid),  // ufix1
                                                        .Pop(AXI4_Stream_Master_TREADY),  // ufix1
                                                        .Out(AXI4_Stream_Master_TDATA_0_1),  // ufix16
                                                        .Empty(fifo_empty_data),  // ufix1
                                                        .AFull(fifo_afull_data)  // ufix1
                                                        );

  assign AXI4_Stream_Master_TDATA_0 = AXI4_Stream_Master_TDATA_0_1;

  PulseDet_fifo_data_OUT_block u_PulseDet_fifo_data_OUT_inst_1 (.clk(clk),
                                                                .reset(reset),
                                                                .enb(enb),
                                                                .In(user_data_1),  // ufix16
                                                                .Push(user_valid),  // ufix1
                                                                .Pop(AXI4_Stream_Master_TREADY),  // ufix1
                                                                .Out(AXI4_Stream_Master_TDATA_1_1)  // ufix16
                                                                );

  assign AXI4_Stream_Master_TDATA_1 = AXI4_Stream_Master_TDATA_1_1;

  assign AXI4_Stream_Master_TVALID =  ~ fifo_empty_data;



  assign const_1 = 32'b00000000000000000000000000000001;



  assign tlast_size_value = write_packet_size_axi4_stream_master - const_1;



  assign reset_TLAST = reg_packet_size_strobe | auto_tlast;



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk)
    begin : tlast_counter_process
      if (reset == 1'b1) begin
        tlast_counter_out <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          if (reset_TLAST == 1'b1) begin
            tlast_counter_out <= 32'b00000000000000000000000000000000;
          end
          else if (user_valid == 1'b1) begin
            tlast_counter_out <= tlast_counter_out + 32'b00000000000000000000000000000001;
          end
        end
      end
    end



  assign relop_relop1 = tlast_counter_out == tlast_size_value;



  assign auto_tlast = user_valid & relop_relop1;



  PulseDet_fifo_TLAST_OUT u_PulseDet_fifo_TLAST_OUT_inst (.clk(clk),
                                                          .reset(reset),
                                                          .enb(enb),
                                                          .In(auto_tlast),  // ufix1
                                                          .Push(user_valid),  // ufix1
                                                          .Pop(AXI4_Stream_Master_TREADY),  // ufix1
                                                          .Out(AXI4_Stream_Master_TLAST)  // ufix1
                                                          );

  assign internal_ready =  ~ fifo_afull_data;



  assign user_ready = internal_ready;

endmodule  // PulseDet_axi4_stream_master

