// Copyright 2025 The MathWorks, Inc.
// -------------------------------------------------------------
// 
// File Name: custom_hdl_prj\hdlsrc\pulse_detector_ipcore\PulseDet_src_Tapped_Delay_Enabled.v
// Created: 2023-08-26 18:01:37
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PulseDet_src_Tapped_Delay_Enabled
// Source Path: pulse_detector_ipcore/Pulse Detector IP/Pulse Detector/Local Peak/Tapped Delay Enabled
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PulseDet_src_Tapped_Delay_Enabled
          (clk,
           reset,
           enb,
           u,
           en,
           y_0,
           y_1,
           y_2,
           y_3,
           y_4,
           y_5,
           y_6,
           y_7,
           y_8,
           y_9,
           y_10);


  input   clk;
  input   reset;
  input   enb;
  input   signed [17:0] u;  // sfix18_En11
  input   en;
  output  signed [17:0] y_0;  // sfix18_En11
  output  signed [17:0] y_1;  // sfix18_En11
  output  signed [17:0] y_2;  // sfix18_En11
  output  signed [17:0] y_3;  // sfix18_En11
  output  signed [17:0] y_4;  // sfix18_En11
  output  signed [17:0] y_5;  // sfix18_En11
  output  signed [17:0] y_6;  // sfix18_En11
  output  signed [17:0] y_7;  // sfix18_En11
  output  signed [17:0] y_8;  // sfix18_En11
  output  signed [17:0] y_9;  // sfix18_En11
  output  signed [17:0] y_10;  // sfix18_En11


  wire signed [17:0] tapped_delay_impl_out1_0;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_1;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_2;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_3;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_4;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_5;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_6;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_7;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_8;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_9;  // sfix18_En11
  wire signed [17:0] tapped_delay_impl_out1_10;  // sfix18_En11
  wire signed [17:0] Reshape_out1_0;  // sfix18_En11
  wire signed [17:0] Reshape_out1_1;  // sfix18_En11
  wire signed [17:0] Reshape_out1_2;  // sfix18_En11
  wire signed [17:0] Reshape_out1_3;  // sfix18_En11
  wire signed [17:0] Reshape_out1_4;  // sfix18_En11
  wire signed [17:0] Reshape_out1_5;  // sfix18_En11
  wire signed [17:0] Reshape_out1_6;  // sfix18_En11
  wire signed [17:0] Reshape_out1_7;  // sfix18_En11
  wire signed [17:0] Reshape_out1_8;  // sfix18_En11
  wire signed [17:0] Reshape_out1_9;  // sfix18_En11
  wire signed [17:0] Reshape_out1_10;  // sfix18_En11


  PulseDet_src_tapped_delay_impl u_tapped_delay_impl (.clk(clk),
                                                      .reset(reset),
                                                      .enb(enb),
                                                      .u(u),  // sfix18_En11
                                                      .en(en),
                                                      .y_0(tapped_delay_impl_out1_0),  // sfix18_En11
                                                      .y_1(tapped_delay_impl_out1_1),  // sfix18_En11
                                                      .y_2(tapped_delay_impl_out1_2),  // sfix18_En11
                                                      .y_3(tapped_delay_impl_out1_3),  // sfix18_En11
                                                      .y_4(tapped_delay_impl_out1_4),  // sfix18_En11
                                                      .y_5(tapped_delay_impl_out1_5),  // sfix18_En11
                                                      .y_6(tapped_delay_impl_out1_6),  // sfix18_En11
                                                      .y_7(tapped_delay_impl_out1_7),  // sfix18_En11
                                                      .y_8(tapped_delay_impl_out1_8),  // sfix18_En11
                                                      .y_9(tapped_delay_impl_out1_9),  // sfix18_En11
                                                      .y_10(tapped_delay_impl_out1_10)  // sfix18_En11
                                                      );

  PulseDet_src_Reshape u_Reshape (.In1_0(tapped_delay_impl_out1_0),  // sfix18_En11
                                  .In1_1(tapped_delay_impl_out1_1),  // sfix18_En11
                                  .In1_2(tapped_delay_impl_out1_2),  // sfix18_En11
                                  .In1_3(tapped_delay_impl_out1_3),  // sfix18_En11
                                  .In1_4(tapped_delay_impl_out1_4),  // sfix18_En11
                                  .In1_5(tapped_delay_impl_out1_5),  // sfix18_En11
                                  .In1_6(tapped_delay_impl_out1_6),  // sfix18_En11
                                  .In1_7(tapped_delay_impl_out1_7),  // sfix18_En11
                                  .In1_8(tapped_delay_impl_out1_8),  // sfix18_En11
                                  .In1_9(tapped_delay_impl_out1_9),  // sfix18_En11
                                  .In1_10(tapped_delay_impl_out1_10),  // sfix18_En11
                                  .Out1_0(Reshape_out1_0),  // sfix18_En11
                                  .Out1_1(Reshape_out1_1),  // sfix18_En11
                                  .Out1_2(Reshape_out1_2),  // sfix18_En11
                                  .Out1_3(Reshape_out1_3),  // sfix18_En11
                                  .Out1_4(Reshape_out1_4),  // sfix18_En11
                                  .Out1_5(Reshape_out1_5),  // sfix18_En11
                                  .Out1_6(Reshape_out1_6),  // sfix18_En11
                                  .Out1_7(Reshape_out1_7),  // sfix18_En11
                                  .Out1_8(Reshape_out1_8),  // sfix18_En11
                                  .Out1_9(Reshape_out1_9),  // sfix18_En11
                                  .Out1_10(Reshape_out1_10)  // sfix18_En11
                                  );

  assign y_0 = Reshape_out1_0;

  assign y_1 = Reshape_out1_1;

  assign y_2 = Reshape_out1_2;

  assign y_3 = Reshape_out1_3;

  assign y_4 = Reshape_out1_4;

  assign y_5 = Reshape_out1_5;

  assign y_6 = Reshape_out1_6;

  assign y_7 = Reshape_out1_7;

  assign y_8 = Reshape_out1_8;

  assign y_9 = Reshape_out1_9;

  assign y_10 = Reshape_out1_10;

endmodule  // PulseDet_src_Tapped_Delay_Enabled

