% datacapture is a generated class used for FPGA Data Capture. datacapture
% connects MATLAB with a FPGA and captures the FPGA internal signals via
% JTAG connection.
% 
% dco = datacapture returns a FPGA Data Capture System object generated by 
% the user. It captures internal signals from an FPGA that contains the FPGA 
% Data Capture HDL IP core, and returns the data to MATLAB over JTAG. 
% 
%  Step method syntax
% [Capture_Window,Trigger_Position,i_data,i_valid,o_data,o_valid,o_detected]=step(dco) connects to the FPGA, and read data from the FPGA.
% 
% datacapture methods:
% step - see above description for use of this method
% release - Allow property value and input characteristics changes, and release connection to FPGA board
% clone - Create datacapture object with same property values
% isLocked - Locked status (logical)
% setNumberofTriggerStages   - Set number of trigger stages
% setTriggerCondition - Set trigger condition for each trigger signal
% setTriggerCombinationOperator - Set trigger combination operator
% setTriggerComparisonOperator - Set trigger comparison operator
% setTriggerTimeout     - Set timeout for each stage
% setDataType - Set signal data type
% displayDataTypes - Display current data type settings
% displayTriggerCondition - Display current trigger condition
% setCaptureCondition - Set capture condition for each trigger signal
% setCaptureConditionCombinationOperator - Set capture condition combination operator
% setCaptureConditionComparisonOperator - Set capture condition comparison operator
% displayCaptureCondition - Display current capture condition
% launchApp - Launch Graphical User Interface (GUI) App for setting data types, triggers, and capture data interactively
% 
% datacapture properties:
% EnableCaptureCtrl - Enable the capture condition logic
% TimeOut - Time to wait before throwing exception, if trigger condition is not met
% TriggerPosition - The number of samples captured before trigger event
% JTAGCableName - Name of the JTAG cable used for data capture
% JTAGChainPosition - JTAG chain position number of the target FPGA
% IRLengthBefore  - Instruction register lengths before FPGA
% IRLengthAfter   - Instruction register lengths after FPGA
% TckFrequency    - JTAG clock frequency in MHz. 
%
% Created: 26-Aug-2023 17:50:40
% Generated by MATLAB 9.13 and HDL Verifier 7.0

classdef datacapture< hdlverifier.FPGADataReader
% Copyright 2025 The MathWorks, Inc.

methods
    function obj = datacapture
        obj.TriggerPosition  =  0;
        obj.NumCaptureWindows  =  1;
        obj.TimeOut          = 10;
        obj.MaxNumTriggerStages  = 1;
        obj.NumTriggerStages  = 1;
        obj.setDataType('Capture_Window','uint32');
        obj.setDataType('Trigger_Position','boolean');
        obj.setDataType('i_data','int32');
        obj.setDataType('i_valid','boolean');
        obj.setDataType('o_data','int32');
        obj.setDataType('o_valid','boolean');
        obj.setDataType('o_detected','boolean');
        setTriggerConditionArray(obj)
    end
end

% !!! Do NOT change any of the constant properties below !!!
properties (Nontunable, Constant)
    % SamplesPerFrame Samples per frame
    SamplesPerFrame = 4096
    BitWidth = [32   1  32   1  32   1   1]
    SignalNames = {'Capture_Window','Trigger_Position','i_data','i_valid','o_data','o_valid','o_detected'}
    IsSignalTrigger = [0  0  0  1  0  1  1]
    IsSignalData = [0  0  1  1  1  1  1]
    IsMetaData = [1  1  0  0  0  0  0]
    % FPGAVendor FPGA vendor
    FPGAVendor = 'Xilinx'
    Connection = 'JTAG'
    IsConditionalCapture  = false;
    % Version
    Version = '1.2'
    % Timestamp
    TimeStamp = '26-Aug-2023 17:50:40'
end

end
