-- Copyright 2025 The MathWorks, Inc.
-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\VHDL\pulse_detector_v4\subFilter.vhd
-- Created: 2024-04-02 19:25:11
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: subFilter
-- Source Path: pulse_detector_v4/Pulse Detector/Discrete FIR Filter/Filter/subFilter
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Pulse_Detector_pkg.ALL;

ENTITY subFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En14
        coefIn                            :   IN    vector_of_std_logic_vector19(0 TO 63);  -- sfix19_En23 [64]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(47 DOWNTO 0);  -- sfix48_En37
        doutVld                           :   OUT   std_logic
        );
END subFilter;


ARCHITECTURE rtl OF subFilter IS

  -- Component Declarations
  COMPONENT FilterTapSystolicWvldin
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En14
          coefIn_0                        :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19_En23
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En37
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En14
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En37
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterTapSystolicWvldin
    USE ENTITY work.FilterTapSystolicWvldin(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(0 TO 66);  -- ufix1 [67]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(47 DOWNTO 0);  -- sfix48_En37
  SIGNAL addin                            : signed(47 DOWNTO 0);  -- sfix48_En37
  SIGNAL dinDly2                          : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout                           : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_1                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_1                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_2                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_2                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_3                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_3                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_4                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_4                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_5                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_5                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_6                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_6                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_7                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_7                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_8                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_8                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_9                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_9                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_10                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_10                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_11                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_11                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_12                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_12                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_13                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_13                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_14                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_14                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_15                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_15                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_16                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_16                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_17                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_17                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_18                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_18                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_19                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_19                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_20                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_20                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_21                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_21                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_22                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_22                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_23                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_23                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_24                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_24                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_25                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_25                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_26                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_26                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_27                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_27                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_28                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_28                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_29                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_29                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_30                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_30                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_31                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_31                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_32                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_32                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_33                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_33                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_34                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_34                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_35                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_35                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_36                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_36                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_37                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_37                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_38                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_38                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_39                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_39                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_40                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_40                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_41                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_41                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_42                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_42                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_43                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_43                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_44                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_44                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_45                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_45                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_46                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_46                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_47                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_47                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_48                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_48                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_49                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_49                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_50                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_50                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_51                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_51                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_52                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_52                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_53                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_53                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_54                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_54                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_55                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_55                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_56                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_56                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_57                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_57                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_58                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_58                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_59                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_59                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_60                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_60                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_61                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_61                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_62                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_62                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2deadOut                   : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_63                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_signed                    : signed(47 DOWNTO 0);  -- sfix48_En37
  SIGNAL muxOut                           : signed(47 DOWNTO 0);  -- sfix48_En37
  SIGNAL dout_1_re_tmp                    : signed(47 DOWNTO 0);  -- sfix48_En37

BEGIN
  u_FilterTap_1 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix17_En14
              coefIn_0 => coefIn(0),  -- sfix19_En23
              addin => std_logic_vector(addin),  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix17_En14
              tapout => tapout  -- sfix48_En37
              );

  u_FilterTap_2 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2,  -- sfix17_En14
              coefIn_0 => coefIn(1),  -- sfix19_En23
              addin => tapout,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_1,  -- sfix17_En14
              tapout => tapout_1  -- sfix48_En37
              );

  u_FilterTap_3 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_1,  -- sfix17_En14
              coefIn_0 => coefIn(2),  -- sfix19_En23
              addin => tapout_1,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_2,  -- sfix17_En14
              tapout => tapout_2  -- sfix48_En37
              );

  u_FilterTap_4 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_2,  -- sfix17_En14
              coefIn_0 => coefIn(3),  -- sfix19_En23
              addin => tapout_2,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_3,  -- sfix17_En14
              tapout => tapout_3  -- sfix48_En37
              );

  u_FilterTap_5 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_3,  -- sfix17_En14
              coefIn_0 => coefIn(4),  -- sfix19_En23
              addin => tapout_3,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_4,  -- sfix17_En14
              tapout => tapout_4  -- sfix48_En37
              );

  u_FilterTap_6 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_4,  -- sfix17_En14
              coefIn_0 => coefIn(5),  -- sfix19_En23
              addin => tapout_4,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_5,  -- sfix17_En14
              tapout => tapout_5  -- sfix48_En37
              );

  u_FilterTap_7 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_5,  -- sfix17_En14
              coefIn_0 => coefIn(6),  -- sfix19_En23
              addin => tapout_5,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_6,  -- sfix17_En14
              tapout => tapout_6  -- sfix48_En37
              );

  u_FilterTap_8 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_6,  -- sfix17_En14
              coefIn_0 => coefIn(7),  -- sfix19_En23
              addin => tapout_6,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_7,  -- sfix17_En14
              tapout => tapout_7  -- sfix48_En37
              );

  u_FilterTap_9 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_7,  -- sfix17_En14
              coefIn_0 => coefIn(8),  -- sfix19_En23
              addin => tapout_7,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_8,  -- sfix17_En14
              tapout => tapout_8  -- sfix48_En37
              );

  u_FilterTap_10 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_8,  -- sfix17_En14
              coefIn_0 => coefIn(9),  -- sfix19_En23
              addin => tapout_8,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_9,  -- sfix17_En14
              tapout => tapout_9  -- sfix48_En37
              );

  u_FilterTap_11 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_9,  -- sfix17_En14
              coefIn_0 => coefIn(10),  -- sfix19_En23
              addin => tapout_9,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_10,  -- sfix17_En14
              tapout => tapout_10  -- sfix48_En37
              );

  u_FilterTap_12 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_10,  -- sfix17_En14
              coefIn_0 => coefIn(11),  -- sfix19_En23
              addin => tapout_10,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_11,  -- sfix17_En14
              tapout => tapout_11  -- sfix48_En37
              );

  u_FilterTap_13 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_11,  -- sfix17_En14
              coefIn_0 => coefIn(12),  -- sfix19_En23
              addin => tapout_11,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_12,  -- sfix17_En14
              tapout => tapout_12  -- sfix48_En37
              );

  u_FilterTap_14 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_12,  -- sfix17_En14
              coefIn_0 => coefIn(13),  -- sfix19_En23
              addin => tapout_12,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_13,  -- sfix17_En14
              tapout => tapout_13  -- sfix48_En37
              );

  u_FilterTap_15 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_13,  -- sfix17_En14
              coefIn_0 => coefIn(14),  -- sfix19_En23
              addin => tapout_13,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_14,  -- sfix17_En14
              tapout => tapout_14  -- sfix48_En37
              );

  u_FilterTap_16 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_14,  -- sfix17_En14
              coefIn_0 => coefIn(15),  -- sfix19_En23
              addin => tapout_14,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_15,  -- sfix17_En14
              tapout => tapout_15  -- sfix48_En37
              );

  u_FilterTap_17 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_15,  -- sfix17_En14
              coefIn_0 => coefIn(16),  -- sfix19_En23
              addin => tapout_15,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_16,  -- sfix17_En14
              tapout => tapout_16  -- sfix48_En37
              );

  u_FilterTap_18 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_16,  -- sfix17_En14
              coefIn_0 => coefIn(17),  -- sfix19_En23
              addin => tapout_16,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_17,  -- sfix17_En14
              tapout => tapout_17  -- sfix48_En37
              );

  u_FilterTap_19 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_17,  -- sfix17_En14
              coefIn_0 => coefIn(18),  -- sfix19_En23
              addin => tapout_17,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_18,  -- sfix17_En14
              tapout => tapout_18  -- sfix48_En37
              );

  u_FilterTap_20 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_18,  -- sfix17_En14
              coefIn_0 => coefIn(19),  -- sfix19_En23
              addin => tapout_18,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_19,  -- sfix17_En14
              tapout => tapout_19  -- sfix48_En37
              );

  u_FilterTap_21 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_19,  -- sfix17_En14
              coefIn_0 => coefIn(20),  -- sfix19_En23
              addin => tapout_19,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_20,  -- sfix17_En14
              tapout => tapout_20  -- sfix48_En37
              );

  u_FilterTap_22 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_20,  -- sfix17_En14
              coefIn_0 => coefIn(21),  -- sfix19_En23
              addin => tapout_20,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_21,  -- sfix17_En14
              tapout => tapout_21  -- sfix48_En37
              );

  u_FilterTap_23 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_21,  -- sfix17_En14
              coefIn_0 => coefIn(22),  -- sfix19_En23
              addin => tapout_21,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_22,  -- sfix17_En14
              tapout => tapout_22  -- sfix48_En37
              );

  u_FilterTap_24 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_22,  -- sfix17_En14
              coefIn_0 => coefIn(23),  -- sfix19_En23
              addin => tapout_22,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_23,  -- sfix17_En14
              tapout => tapout_23  -- sfix48_En37
              );

  u_FilterTap_25 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_23,  -- sfix17_En14
              coefIn_0 => coefIn(24),  -- sfix19_En23
              addin => tapout_23,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_24,  -- sfix17_En14
              tapout => tapout_24  -- sfix48_En37
              );

  u_FilterTap_26 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_24,  -- sfix17_En14
              coefIn_0 => coefIn(25),  -- sfix19_En23
              addin => tapout_24,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_25,  -- sfix17_En14
              tapout => tapout_25  -- sfix48_En37
              );

  u_FilterTap_27 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_25,  -- sfix17_En14
              coefIn_0 => coefIn(26),  -- sfix19_En23
              addin => tapout_25,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_26,  -- sfix17_En14
              tapout => tapout_26  -- sfix48_En37
              );

  u_FilterTap_28 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_26,  -- sfix17_En14
              coefIn_0 => coefIn(27),  -- sfix19_En23
              addin => tapout_26,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_27,  -- sfix17_En14
              tapout => tapout_27  -- sfix48_En37
              );

  u_FilterTap_29 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_27,  -- sfix17_En14
              coefIn_0 => coefIn(28),  -- sfix19_En23
              addin => tapout_27,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_28,  -- sfix17_En14
              tapout => tapout_28  -- sfix48_En37
              );

  u_FilterTap_30 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_28,  -- sfix17_En14
              coefIn_0 => coefIn(29),  -- sfix19_En23
              addin => tapout_28,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_29,  -- sfix17_En14
              tapout => tapout_29  -- sfix48_En37
              );

  u_FilterTap_31 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_29,  -- sfix17_En14
              coefIn_0 => coefIn(30),  -- sfix19_En23
              addin => tapout_29,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_30,  -- sfix17_En14
              tapout => tapout_30  -- sfix48_En37
              );

  u_FilterTap_32 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_30,  -- sfix17_En14
              coefIn_0 => coefIn(31),  -- sfix19_En23
              addin => tapout_30,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_31,  -- sfix17_En14
              tapout => tapout_31  -- sfix48_En37
              );

  u_FilterTap_33 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_31,  -- sfix17_En14
              coefIn_0 => coefIn(32),  -- sfix19_En23
              addin => tapout_31,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_32,  -- sfix17_En14
              tapout => tapout_32  -- sfix48_En37
              );

  u_FilterTap_34 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_32,  -- sfix17_En14
              coefIn_0 => coefIn(33),  -- sfix19_En23
              addin => tapout_32,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_33,  -- sfix17_En14
              tapout => tapout_33  -- sfix48_En37
              );

  u_FilterTap_35 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_33,  -- sfix17_En14
              coefIn_0 => coefIn(34),  -- sfix19_En23
              addin => tapout_33,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_34,  -- sfix17_En14
              tapout => tapout_34  -- sfix48_En37
              );

  u_FilterTap_36 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_34,  -- sfix17_En14
              coefIn_0 => coefIn(35),  -- sfix19_En23
              addin => tapout_34,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_35,  -- sfix17_En14
              tapout => tapout_35  -- sfix48_En37
              );

  u_FilterTap_37 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_35,  -- sfix17_En14
              coefIn_0 => coefIn(36),  -- sfix19_En23
              addin => tapout_35,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_36,  -- sfix17_En14
              tapout => tapout_36  -- sfix48_En37
              );

  u_FilterTap_38 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_36,  -- sfix17_En14
              coefIn_0 => coefIn(37),  -- sfix19_En23
              addin => tapout_36,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_37,  -- sfix17_En14
              tapout => tapout_37  -- sfix48_En37
              );

  u_FilterTap_39 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_37,  -- sfix17_En14
              coefIn_0 => coefIn(38),  -- sfix19_En23
              addin => tapout_37,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_38,  -- sfix17_En14
              tapout => tapout_38  -- sfix48_En37
              );

  u_FilterTap_40 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_38,  -- sfix17_En14
              coefIn_0 => coefIn(39),  -- sfix19_En23
              addin => tapout_38,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_39,  -- sfix17_En14
              tapout => tapout_39  -- sfix48_En37
              );

  u_FilterTap_41 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_39,  -- sfix17_En14
              coefIn_0 => coefIn(40),  -- sfix19_En23
              addin => tapout_39,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_40,  -- sfix17_En14
              tapout => tapout_40  -- sfix48_En37
              );

  u_FilterTap_42 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_40,  -- sfix17_En14
              coefIn_0 => coefIn(41),  -- sfix19_En23
              addin => tapout_40,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_41,  -- sfix17_En14
              tapout => tapout_41  -- sfix48_En37
              );

  u_FilterTap_43 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_41,  -- sfix17_En14
              coefIn_0 => coefIn(42),  -- sfix19_En23
              addin => tapout_41,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_42,  -- sfix17_En14
              tapout => tapout_42  -- sfix48_En37
              );

  u_FilterTap_44 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_42,  -- sfix17_En14
              coefIn_0 => coefIn(43),  -- sfix19_En23
              addin => tapout_42,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_43,  -- sfix17_En14
              tapout => tapout_43  -- sfix48_En37
              );

  u_FilterTap_45 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_43,  -- sfix17_En14
              coefIn_0 => coefIn(44),  -- sfix19_En23
              addin => tapout_43,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_44,  -- sfix17_En14
              tapout => tapout_44  -- sfix48_En37
              );

  u_FilterTap_46 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_44,  -- sfix17_En14
              coefIn_0 => coefIn(45),  -- sfix19_En23
              addin => tapout_44,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_45,  -- sfix17_En14
              tapout => tapout_45  -- sfix48_En37
              );

  u_FilterTap_47 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_45,  -- sfix17_En14
              coefIn_0 => coefIn(46),  -- sfix19_En23
              addin => tapout_45,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_46,  -- sfix17_En14
              tapout => tapout_46  -- sfix48_En37
              );

  u_FilterTap_48 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_46,  -- sfix17_En14
              coefIn_0 => coefIn(47),  -- sfix19_En23
              addin => tapout_46,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_47,  -- sfix17_En14
              tapout => tapout_47  -- sfix48_En37
              );

  u_FilterTap_49 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_47,  -- sfix17_En14
              coefIn_0 => coefIn(48),  -- sfix19_En23
              addin => tapout_47,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_48,  -- sfix17_En14
              tapout => tapout_48  -- sfix48_En37
              );

  u_FilterTap_50 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_48,  -- sfix17_En14
              coefIn_0 => coefIn(49),  -- sfix19_En23
              addin => tapout_48,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_49,  -- sfix17_En14
              tapout => tapout_49  -- sfix48_En37
              );

  u_FilterTap_51 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_49,  -- sfix17_En14
              coefIn_0 => coefIn(50),  -- sfix19_En23
              addin => tapout_49,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_50,  -- sfix17_En14
              tapout => tapout_50  -- sfix48_En37
              );

  u_FilterTap_52 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_50,  -- sfix17_En14
              coefIn_0 => coefIn(51),  -- sfix19_En23
              addin => tapout_50,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_51,  -- sfix17_En14
              tapout => tapout_51  -- sfix48_En37
              );

  u_FilterTap_53 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_51,  -- sfix17_En14
              coefIn_0 => coefIn(52),  -- sfix19_En23
              addin => tapout_51,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_52,  -- sfix17_En14
              tapout => tapout_52  -- sfix48_En37
              );

  u_FilterTap_54 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_52,  -- sfix17_En14
              coefIn_0 => coefIn(53),  -- sfix19_En23
              addin => tapout_52,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_53,  -- sfix17_En14
              tapout => tapout_53  -- sfix48_En37
              );

  u_FilterTap_55 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_53,  -- sfix17_En14
              coefIn_0 => coefIn(54),  -- sfix19_En23
              addin => tapout_53,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_54,  -- sfix17_En14
              tapout => tapout_54  -- sfix48_En37
              );

  u_FilterTap_56 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_54,  -- sfix17_En14
              coefIn_0 => coefIn(55),  -- sfix19_En23
              addin => tapout_54,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_55,  -- sfix17_En14
              tapout => tapout_55  -- sfix48_En37
              );

  u_FilterTap_57 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_55,  -- sfix17_En14
              coefIn_0 => coefIn(56),  -- sfix19_En23
              addin => tapout_55,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_56,  -- sfix17_En14
              tapout => tapout_56  -- sfix48_En37
              );

  u_FilterTap_58 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_56,  -- sfix17_En14
              coefIn_0 => coefIn(57),  -- sfix19_En23
              addin => tapout_56,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_57,  -- sfix17_En14
              tapout => tapout_57  -- sfix48_En37
              );

  u_FilterTap_59 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_57,  -- sfix17_En14
              coefIn_0 => coefIn(58),  -- sfix19_En23
              addin => tapout_57,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_58,  -- sfix17_En14
              tapout => tapout_58  -- sfix48_En37
              );

  u_FilterTap_60 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_58,  -- sfix17_En14
              coefIn_0 => coefIn(59),  -- sfix19_En23
              addin => tapout_58,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_59,  -- sfix17_En14
              tapout => tapout_59  -- sfix48_En37
              );

  u_FilterTap_61 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_59,  -- sfix17_En14
              coefIn_0 => coefIn(60),  -- sfix19_En23
              addin => tapout_59,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_60,  -- sfix17_En14
              tapout => tapout_60  -- sfix48_En37
              );

  u_FilterTap_62 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_60,  -- sfix17_En14
              coefIn_0 => coefIn(61),  -- sfix19_En23
              addin => tapout_60,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_61,  -- sfix17_En14
              tapout => tapout_61  -- sfix48_En37
              );

  u_FilterTap_63 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_61,  -- sfix17_En14
              coefIn_0 => coefIn(62),  -- sfix19_En23
              addin => tapout_61,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_62,  -- sfix17_En14
              tapout => tapout_62  -- sfix48_En37
              );

  u_FilterTap_64 : FilterTapSystolicWvldin
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_62,  -- sfix17_En14
              coefIn_0 => coefIn(63),  -- sfix19_En23
              addin => tapout_62,  -- sfix48_En37
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2deadOut,  -- sfix17_En14
              tapout => tapout_63  -- sfix48_En37
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(1 TO 66) <= intdelay_reg(0 TO 65);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(66);

  vldOutTmp <= dinRegVld AND vldShift;

  ZERO_OUT <= to_signed(0, 48);

  addin <= to_signed(0, 48);

  tapout_signed <= signed(tapout_63);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      tapout_signed;

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re_tmp <= to_signed(0, 48);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(0, 48);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        doutVld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          doutVld <= '0';
        ELSE 
          doutVld <= vldOutTmp;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


END rtl;

